name: auto-build-spider-proxy-ha-release
on:
  # åªé’ˆå¯¹ä»¥vå¼€å¤´çš„tagå‘å¸ƒè‡ªåŠ¨æ‰“åŒ…ï¼Œä¾‹å¦‚v1.0
  tags:
    - 'v*'
jobs:
  build-and-public-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # ç¬¬ä¸€æ­¥ï¼šä¸‹è½½æºç 
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      # ç¬¬äºŒæ­¥ï¼šæ‰“åŒ…æ„å»º
      - name: setup jdk
        uses: actions/setup-java@v2
          with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build spider-proxy-ha-core with Maven
        run: |
          cd spider-ha-proxy-core
          mvn -B clean -P prod -Dmaven.test.skip=true package appassembler:assemble
      - name: zip spider-proxy-ha-core
        run: |
          mv spider-ha-proxy-core-1.0.jar dist-spider-proxy-ha
      - run: echo "ğŸ This job's status is ${{ job.status }}."
