name: auto-build-spider-proxy-ha-release
on:
  push:
    paths:
      - 'release.json'
jobs:
  build-and-public-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # ç¬¬ä¸€æ­¥ï¼šä¸‹è½½æºç 
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      # ç¬¬äºŒæ­¥ï¼šæ‰“åŒ…æ„å»º
      - name: setup jdk
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      # è¯»å–coreç‰ˆæœ¬
      - name: read version of proxy-core
        id: versions-core
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./release.json
          property: proxy-core-version
      - run: echo "ğŸ read version of proxy-core ${{ steps.versions-core.outputs.value }}."
      # è¯»å–mockerç‰ˆæœ¬
      - name: read version of upstream-mocker
        id: versions-mocker
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./release.json
          property: upstream-mocker-version
      - run: echo "ğŸ read version of upstream-mocker ${{ steps.versions-mocker.outputs.value }}."
      # è¯»å–tagå·
      - name: read version of tag
        id: versions-tag
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./release.json
          property: tag-version
      - run: echo "ğŸ read version of tag ${{ steps.versions-tag.outputs.value }}."
      # æ„å»ºspider-proxy-ha-core
      - name: Build spider-proxy-ha-core with Maven
        run: |
          cd spider-ha-proxy-core
          mvn -B clean -P prod -Dmaven.test.skip=true package appassembler:assemble
      - run: echo "ğŸ maven build spider-proxy-core success."
      # æ‰“åŒ…spider-proxy-ha-core
      - run: mv target/spider-ha-proxy-core-${{ steps.versions-core.outputs.value }}.jar target/dist-spider-proxy-ha
      - run: ls -l ./
      - name: zip spider-proxy-ha-core
        uses: thedoctor0/zip-release@master
        with:
          fliename: "spider-proxy-ha-${{ steps.versions-core.outputs.value }}.zip"
          path: target/dist-spider-proxy-ha
      - run: echo "ğŸ zip spider-proxy-core success spider-proxy-ha-${{ steps.versions-core.outputs.value }}.zip"
      # æ„å»ºupstream-mocker
      - name: Build upstream-mocker with Maven
        run: |
          cd ../upstream-mocker
          mvn -B clean -Dmaven.test.skip=true package appassembler:assemble
      - run: echo "ğŸ maven build upstream-mocker success."
      # æ‰“åŒ…upstream-mocker
      - run: mv target/upstream-mocker-${{ steps.versions-mocker.outputs.value }}.jar target/dist-mocker
      - name: zip upstream-mocker
        uses: thedoctor0/zip-release@master
        with:
          fliename: "upstream-mocker-${{ steps.versions-mocker.outputs.value }}.zip"
          path: target/dist-mocker
      - run: echo "ğŸ zip spider-proxy-core success upstream-mocker-${{ steps.versions-mocker.outputs.value }}.jar.zip"
      - name: create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versions-tag.outputs.value }}
          release_name: Release ${{ steps.versions-tag.outputs.value }}
          draft: false
          prerelease: false
      - run: echo "ğŸ create release success ${{ steps.versions-tag.outputs.value }}"
      # ä¸Šä¼ release
      - name: upload mocker release asstes
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./upstream-mocker-${{ steps.versions-mocker.outputs.value }}.zip
          asset_name: upstream-mocker-${{ steps.versions-mocker.outputs.value }}.zip
          asset_content_type: application/zip
      - name: upload core release asstes
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./spider-ha-proxy-core-${{ steps.versions-core.outputs.value }}.zip
          asset_name: spider-ha-proxy-core-${{ steps.versions-core.outputs.value }}.zip
          asset_content_type: application/zip
      - run: echo "ğŸ This job's status is ${{ job.status }}."
